export const lindeProducts = [
  {
    id: 1,
    description: "M10 X/XE",
    lifting_capacity_kg: "0-1000",
    lifting_height_mm: "0-715",
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "01 M10X:XE",
    photo: "01_M10X_XE",
  },
  {
    id: 2,
    description: "MT15 C",
    lifting_capacity_kg: "0-1500",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "02 MT15C",
    photo: "02_MT15C",
  },
  {
    id: 3,
    description: "MT15",
    lifting_capacity_kg: "0-1500",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "03 MT15",
    photo: "03_MT15",
  },
  {
    id: 4,
    description: "M25",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-115",
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "04 M25",
    photo: "04_M25",
  },
  {
    id: 5,
    description: "M25 Scale+",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-115",
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "05 M25Scale",
    photo: "05_M25Scale",
  },
  {
    id: 6,
    description: "T14 B",
    lifting_capacity_kg: "0-1400",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "06 T14B",
    photo: "06_T14B",
  },
  {
    id: 7,
    description: "T14 – T20",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "07 T14-T20",
    photo: "07_T14-T20",
  },
  {
    id: 8,
    description: "T16 L",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-675",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "08 T16L",
    photo: "08_T16L",
  },
  {
    id: 9,
    description: "T25 – T30",
    lifting_capacity_kg: "0-3000",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "09 T25-T30",
    photo: "09_T25-T30",
  },
  {
    id: 10,
    description: "T16 – T20 P",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "10 T16 T20P",
    photo: "10_T16_T20P",
  },
  {
    id: 11,
    description: "T20 – T25 AP N",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "11 T20-T25APN",
    photo: "11_T20-T25APN",
  },
  {
    id: 12,
    description: "T20 – T25 AP",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "12 T20-T25AP",
    photo: "12_T20-T25AP",
  },
  {
    id: 13,
    description: "T20 – T25 FP",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "13 T20-T25FP",
    photo: "13_T20-T25FP",
  },
  {
    id: 14,
    description: "T20 – T25 SP",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "14 T20-T25SP",
    photo: "14_T20-T25SP",
  },
  {
    id: 15,
    description: "T20 – T25 SR",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "15 T20-T25SR",
    photo: "15_T20-T25SR",
  },
  {
    id: 16,
    description: "T14 S – T25 S/F",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "16 T20-T25S:F",
    photo: "16_T20-T25S:F",
  },
  {
    id: 17,
    description: "T20 – T25 R",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-115",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "17 T20-T25R",
    photo: "17_T20-T25R",
  },
  {
    id: 18,
    description: "T20 – T25 RW",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-125",
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "18 T20-T25RW",
    photo: "18_T20-T25RW",
  },
  {
    id: 19,
    description: "P20",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0",
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "19 P20",
    photo: "19_P20",
  },
  {
    id: 20,
    description: "P40 – P60 C",
    lifting_capacity_kg: "0-6000",
    lifting_height_mm: "0",
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "20 P40-P60C",
    photo: "20_P40-P60C",
  },
  {
    id: 21,
    description: "P60 – P80",
    lifting_capacity_kg: "0-200",
    lifting_height_mm: "0",
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "21 P60-P80",
    photo: "21_P60-P80",
  },
  {
    id: 22,
    description: "P120 – P350",
    lifting_capacity_kg: "0-300",
    lifting_height_mm: "0",
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "22 P120-P350",
    photo: "22_P120-P350",
  },
  {
    id: 23,
    description: "W20 – W30",
    lifting_capacity_kg: "0-3000",
    lifting_height_mm: "0",
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "23 W20-W30",
    photo: "23_W20-W30",
  },
  {
    id: 24,
    description: "R10 – R16 B",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-7710",
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "24 R 10-R16B",
    photo: "24_R10-R16B",
  },
  {
    id: 25,
    description: "R14 – R25",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-14955",
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: true,
    pdf_file: "25 R14-R25",
    photo: "25_R14-R25",
  },
  {
    id: 26,
    description: "R14 – R20 G",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-7710",
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "26 R14-R20G",
    photo: "26_R14-R20G",
  },
  {
    id: 27,
    description: "R14 – R17 X",
    lifting_capacity_kg: "0-1700",
    lifting_height_mm: "0-12755",
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "27 R14-R17X",
    photo: "27_R14-R17X",
  },
  {
    id: 28,
    description: "R20 – R25 F",
    lifting_capacity_kg: "0-2500",
    lifting_height_mm: "0-9650",
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "28 R20-R25F",
    photo: "28_R20-R25F",
  },
  {
    id: 29,
    description: "A",
    lifting_capacity_kg: "0-1500",
    lifting_height_mm: "0-12850",
    movement_system: "Elektrik",
    product_type: "Stivues per hapsira te ngushta",
    ex_protection: false,
    pdf_file: "29 A",
    photo: "29_A",
  },
  {
    id: 30,
    description: "K",
    lifting_capacity_kg: "0-1500",
    lifting_height_mm: "0-18110",
    movement_system: "Elektrik",
    product_type: "Stivues per hapsira te ngushta",
    ex_protection: true,
    pdf_file: "30 K",
    photo: "30_K",
  },
  {
    id: 31,
    description: "ML10 / MM10",
    lifting_capacity_kg: "0-1000",
    lifting_height_mm: "0-3227",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "31 ML10:MM10",
    photo: "31_ML10:MM10",
  },
  {
    id: 32,
    description: "L10 – L16 B",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-5466",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "32 L10-L16B",
    photo: "32_L10-L16B",
  },
  {
    id: 33,
    description: "L14 – L20",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-6216",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "33 L14-L20",
    photo: "33_L14-L20",
  },
  {
    id: 34,
    description: "L14 – L20 AP",
    lifting_capacity_kg: "0-2000",
    lifting_height_mm: "0-6216",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "34 L14-L20AP",
    photo: "34_L14-L20AP",
  },
  {
    id: 35,
    description: "L14 – L16 SP",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-5316",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "35 L14-L16SP",
    photo: "35_L14-L16SP",
  },
  {
    id: 36,
    description: "L14 – L16 R/Ri",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-5316",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "36 L14-L16R:RI",
    photo: "36_L14-L16R:RI",
  },
  {
    id: 37,
    description: "L14 – L16 RW",
    lifting_capacity_kg: "0-1600",
    lifting_height_mm: "0-6216",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "37 L14-L16RW",
    photo: "37_L14-L16RW",
  },
  {
    id: 38,
    description: "L10 – L12 B AS",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 4,686",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "38 L10-L12BAS",
    photo: "38_L10-L12BAS",
  },
  {
    id: 39,
    description: "L14 – L16 AS/AS AP",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 5,316",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "39 L14-L16AS:ASAP",
    photo: "39_L14-L16AS:ASAP",
  },
  {
    id: 40,
    description: "L06 – L16 AC",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 4,266",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "40 L06-L16AC",
    photo: "40_L06-L16AC",
  },
  {
    id: 41,
    description: "D06 – D10",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 2,024",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "41 D06-D10",
    photo: "41_D06-D10",
  },
  {
    id: 42,
    description: "D08 M",
    lifting_capacity_kg: "0 - 1,800",
    lifting_height_mm: "0 - 1,590",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "42 D08M",
    photo: "42_D08M",
  },
  {
    id: 43,
    description: "D10",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 2,424",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "43 D10",
    photo: "43_D10",
  },
  {
    id: 44,
    description: "D10 AP",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 2,424",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "44 D10AP",
    photo: "44_D10AP",
  },
  {
    id: 45,
    description: "D10 FP",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 2,424",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "45 D10FP",
    photo: "45_D10FP",
  },
  {
    id: 46,
    description: "D12 – D14",
    lifting_capacity_kg: "0 - 1,400",
    lifting_height_mm: "0 - 4,266",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "46 D12-D14",
    photo: "46_D12-D14",
  },
  {
    id: 47,
    description: "D12 – D14 AP",
    lifting_capacity_kg: "0 - 1,400",
    lifting_height_mm: "0 - 4,266",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "47 D12-D14AP",
    photo: "47_D12-D14AP",
  },
  {
    id: 48,
    description: "D12 HP AP",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 2,424",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "48 D12HPAP",
    photo: "48_D12HPAP",
  },
  {
    id: 49,
    description: "D12 – D14 SP",
    lifting_capacity_kg: "0 - 1,400",
    lifting_height_mm: "0 - 4,266",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "49 D12-D14SP",
    photo: "49_D12-D14SP",
  },
  {
    id: 50,
    description: "D12 HP SP",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 2,424",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "50 D12HPSP",
    photo: "50_D12HPSP",
  },
  {
    id: 51,
    description: "D12 S – D12 SF",
    lifting_capacity_kg: "0 - 1,800",
    lifting_height_mm: "0 - 1,724",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "51 D12S-D12SF",
    photo: "51_D12S-D12SF",
  },
  {
    id: 52,
    description: "D12 R",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 2,344",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "52 D12R",
    photo: "52_D12R",
  },
  {
    id: 53,
    description: "D12 RW",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 2,844",
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "53 D12RW",
    photo: "53_D12RW",
  },
  {
    id: 54,
    description: "N20 – N25 HP",
    lifting_capacity_kg: "0 - 2,500",
    lifting_height_mm: "0 - 115",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "54 N20-N25HP",
    photo: "54_N20-N25HP",
  },
  {
    id: 55,
    description: "N16 Li",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 675",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "55 N16LI",
    photo: "55_N16LI",
  },
  {
    id: 56,
    description: "N20 D",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 1,924",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "56 N20D",
    photo: "56_N20D",
  },
  {
    id: 57,
    description: "N20 LoL",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 1,612",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "57 N20LoL",
    photo: "57_N20LoL",
  },
  {
    id: 58,
    description: "N20 XL",
    lifting_capacity_kg: "0 - 600",
    lifting_height_mm: "0 - 750",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "58 N20XL",
    photo: "58_N20XL",
  },
  {
    id: 59,
    description: "N20 – N25 C",
    lifting_capacity_kg: "0 - 2,500",
    lifting_height_mm: "0 - 130",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "59 N20-N25C",
    photo: "59_N20-N25C",
  },
  {
    id: 60,
    description: "N20 C L",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 700",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "60 N20CL",
    photo: "60_N20CL",
  },
  {
    id: 61,
    description: "N20 C D",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 1,580",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "61 N20CD",
    photo: "61_N20CD",
  },
  {
    id: 62,
    description: "N20 C LoL",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 800",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "62 N20CLoL",
    photo: "62_N20CLoL",
  },
  {
    id: 63,
    description: "N20 C LX",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 700",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "63N20CLX",
    photo: "63N20CLX",
  },
  {
    id: 64,
    description: "V08",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 1,877",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "64 V08",
    photo: "64_V08",
  },
  {
    id: 65,
    description: "V10",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 5,415",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "65 V10",
    photo: "65_V10",
  },
  {
    id: 66,
    description: "V modular B",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 6,865",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "66 VmodularB",
    photo: "66_VmodularB",
  },
  {
    id: 67,
    description: "V modular",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 12,660",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "67 Vmodular",
    photo: "67_Vmodular",
  },
  {
    id: 68,
    description: "MV01",
    lifting_capacity_kg: "0 - 100",
    lifting_height_mm: "0 - 3,620",
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "68 MV01",
    photo: "68_MV01",
  },
  {
    id: 69,
    description: "E 10",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 5,400",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "69 E10",
    photo: "69_E10",
  },
  {
    id: 70,
    description: "Xi10 – Xi20",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 8,000",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "70 Xi10-Xi20",
    photo: "70_Xi10-Xi20",
  },
  {
    id: 71,
    description: "E14 – E20",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 8,000",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "71 E14-E20",
    photo: "71_E14-E20",
  },
  {
    id: 72,
    description: "Xi16 – Xi20 P",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 8,000",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "72 Xi16-Xi20P",
    photo: "72_Xi16-Xi20P",
  },
  {
    id: 73,
    description: "E16 – E20 P",
    lifting_capacity_kg: "0 - 2,000",
    lifting_height_mm: "0 - 8,000",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "73 E16-E20P",
    photo: "73_E16-E20P",
  },
  {
    id: 74,
    description: "X20 – X35",
    lifting_capacity_kg: "0 - 3,500",
    lifting_height_mm: "0 - 7,780",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "74 X20-X35",
    photo: "74_X20-X35",
  },
  {
    id: 75,
    description: "E20 – E35",
    lifting_capacity_kg: "0 - 3,500",
    lifting_height_mm: "0 - 7,780",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: true,
    pdf_file: "no datasheet",
    photo: "75_E20-E35",
  },
  {
    id: 76,
    description: "X35 – X50",
    lifting_capacity_kg: "0 - 5,000",
    lifting_height_mm: "0 - 7,665",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "76 X35-X50",
    photo: "76_X35-X50",
  },
  {
    id: 77,
    description: "E35 – E50",
    lifting_capacity_kg: "0 - 5,000",
    lifting_height_mm: "0 - 7,665",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: true,
    pdf_file: "77 E35-E50",
    photo: "77_E35-E50",
  },
  {
    id: 78,
    description: "E60 – E80",
    lifting_capacity_kg: "0 - 8,000",
    lifting_height_mm: "0 - 8,670",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "78 E60-E80",
    photo: "78_E60-E80",
  },
  {
    id: 79,
    description: "E100 – E180",
    lifting_capacity_kg: "0 - 18,000",
    lifting_height_mm: "0 - 7,000",
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "79 E100-E180",
    photo: "79_E100-E180",
  },
  {
    id: 80,
    description: "H16 – H20",
    lifting_capacity_kg: "0 - 2,050",
    lifting_height_mm: "0 - 6,475",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "no datasheet",
    photo: "80_H16-H20",
  },
  {
    id: 81,
    description: "H20 – H35",
    lifting_capacity_kg: "0 - 3,500",
    lifting_height_mm: "0 - 7,780",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "81 H20-H35",
    photo: "81_H20-H35",
  },
  {
    id: 82,
    description: "H35 – H50",
    lifting_capacity_kg: "0 - 5,000",
    lifting_height_mm: "0 - 7,665",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "82 H35-H50",
    photo: "82_H35-H50",
  },
  {
    id: 83,
    description: "H50 – H80",
    lifting_capacity_kg: "0 - 8,000",
    lifting_height_mm: "0 - 9,655",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "83 H50-H80",
    photo: "83_H50-H80",
  },
  {
    id: 84,
    description: "H100 – H180 D",
    lifting_capacity_kg: "0 - 18,000",
    lifting_height_mm: "0 - 9,500",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "84 H100-H180D",
    photo: "84_H100-H180D",
  },
  {
    id: 85,
    description: "HT100 – HT180 D",
    lifting_capacity_kg: "0 - 18,000",
    lifting_height_mm: "0 - 9,500",
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "85 HT100-HT180D",
    photo: "85_HT100-HT180D",
  },
  {
    id: 86,
    description: "LT06 – LT10 M / LT10 W",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 40",
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "86 LT06-LT10M:LT10W",
    photo: "86_LT06-LT10M:LT10W",
  },
  {
    id: 87,
    description: "LT10 – LT20 C / LT10 – LT16 B/BM",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 60",
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "87 LT10-LT20C:LT10-LT16B:BM",
    photo: "87_LT10-LT20C:LT10-LT16B:BM",
  },
  {
    id: 88,
    description: "LT16 Ch/BMh",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 115",
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "88 LT16Ch:BMh",
    photo: "88_LT16Ch:BMh",
  },
  {
    id: 89,
    description: "C-MATIC",
    lifting_capacity_kg: "0 - 1,500",
    lifting_height_mm: "0 - 60",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "89 C-MATIC",
    photo: "89_C-MATIC",
  },
  {
    id: 90,
    description: "C-MATIC HP",
    lifting_capacity_kg: "0 - 1,000",
    lifting_height_mm: "0 - 40",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "90 C-MATICHP",
    photo: "90_C-MATICHP",
  },
  {
    id: 91,
    description: "L-MATIC core",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 1,844",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "91 L-MATICcore",
    photo: "91_L-MATICcore",
  },
  {
    id: 92,
    description: "L-MATIC",
    lifting_capacity_kg: "0 - 1,200",
    lifting_height_mm: "0 - 1,924",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "92 L-MATIC",
    photo: "92_L-MATIC",
  },
  {
    id: 93,
    description: "L-MATIC HD/HD k",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 3,500",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "93 L-MATICHD:HDk",
    photo: "93_L-MATICHD:HDk",
  },
  {
    id: 94,
    description: "L-MATIC AC",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 4,144",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "94 L-MATICAC",
    photo: "94_L-MATICAC",
  },
  {
    id: 95,
    description: "P-MATIC",
    lifting_capacity_kg: "0 - 5,000",
    lifting_height_mm: "0 - 0",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "95 P-MATIC",
    photo: "95_P-MATIC",
  },
  {
    id: 96,
    description: "R-MATIC",
    lifting_capacity_kg: "0 - 1,600",
    lifting_height_mm: "0 - 11,455",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "96 R-MATIC",
    photo: "96_R-MATIC",
  },
  {
    id: 97,
    description: "K-MATIC",
    lifting_capacity_kg: "0 - 1,450",
    lifting_height_mm: "0 - 14,000",
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "97 K-MATIC",
    photo: "97_K-MATIC",
  },
];
