export const lindeProducts = [
  {
    id: 1,
    description: "M10 X/XE",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 715,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "01 M10X:XE",
    photo: "01_M10X_XE",
  },
  {
    id: 2,
    description: "MT15 C",
    lifting_capacity_kg: 1500,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "02 MT15C",
    photo: "02_MT15C",
  },
  {
    id: 3,
    description: "MT15",
    long_description:
      'Transpaleta elektrike LINDE e serisë MT15 që ka një strukturë kompakte. Ajo mund të merret me vete në kamionët e transportimit të ngarkesave sepse është shumë e manovrushme sidomos në hapësirat e ngushta. Operatori i transpaletës nuk duhet të shpenzojë shumë energji për përpunimin e ngarkesave pasi këto transpaleta janë të pajisura me motorë të fuqishëm elektrik. Komandimi i këtyre transpaletave është i thjeshtë dhe mund të realizohet edhe me një dorë, falë çelësave që ajo ka në dorezë. Timoni i komandimit është i gjatë, ndaj dhe ofron siguri gjatë përdorimit. Këto pajisje kanë frena elektro-magnetike të cilat zvogëlojnë shpejtësinë e lëvizjes kur çelësi "flutur" i komandimit të lëvizjes, lëshohet. Struktura e telaios së transpaletave LINDE të serisë MT15 është e ulët, ndaj dhe nuk lejon që këmbët e operatorit të hyjnë poshtë pajisjes. Motori elektrik është i mbrojtur nga një veshje metalike për të eleminuar mundësinë e dëmtimit të tij si rezultat i goditjeve. Transpaletat LINDE të serisë MT15 mund të ngrenë dhe transportojnë ngarkesa me peshë deri në 1500 kg.',
    lifting_capacity_kg: 1500,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "03 MT15",
    photo: "03_MT15",
  },
  {
    id: 4,
    description: "M25",
    long_description:
      "Transpaletat LINDE e tipit M25 kanë një strukturë të fortë dhe nuk përkulet nga ngarkesat e rënda. Struktura prej çeliku e saj duron rreth 25% më shumë se modelet e markave të tjera të këtyre përmasave. Hidraulika e transpaletave M25 është e mbrojtur nga pluhurat dhe i përshtatet mirë përdorimit gjatë gjithë ditës së punës. Mirëmbajtja e këtyre transpaletave është minimale. Rrotat dhe rrulat rrisin kapacitetin e lëvizjes falë koefiçientit të ulët të fërkimit. Timoni i këtyre pajisjeve mund të rrotullohet në një kënd të gjerë nga të dy anët. Për këtë arsye transpaletat M25 manovrohen lehtësisht edhe në hapësira të ngushta. Doreza e gjerë e kësaj pajisje mbron duart e operatorit nga dëmtimet e mundshme. Këto transpaleta kanë një kapacitet ngritës deri në 2500 kg.",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 115,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "04 M25",
    photo: "04_M25",
  },
  {
    id: 5,
    description: "M25 Scale+",
    long_description:
      "Transpaletat LINDE të serisë M25 Scale+ kanë të integruar një peshore me gabim në matje me vetëm 500 gram. Kjo do të thotë që përdoruesve të tyre u kursehet një lëvizje për deri tek peshoret e jashtëme, pra kursehet kohë gjatë përpunimit të ngarkesave. LINDE ofron edhe printera me skedë memorie për ato përdorues që dëshirojnë të ruajnë peshat e matura. Këto transpaleta kanë një strukturë të fortë dhe garantojnë një efektivitet të lartë në punë. Ato janë shumë të manovrueshme dhe kanë një qëndrushmëri shumë të mirë. Për këtë arsye ato janë në gjendje të shërbejnë për një kohë të gjatë pa patur nevojë për mirëmbajtje. Duart e operatorit janë të mbrojtura nga një dorezë e gjerë. Transpaletat LINDE të tipit M25 Scale+ mund të ngrenë dhe të transportojnë ngarkesa me peshë deri në 2500 kg.",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 115,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "05 M25Scale",
    photo: "05_M25Scale",
  },
  {
    id: 6,
    description: "T14 B",
    lifting_capacity_kg: 1400,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "06 T14B",
    photo: "06_T14B",
  },
  {
    id: 7,
    description: "T14 – T20",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "07 T14-T20",
    photo: "07_T14-T20",
  },
  {
    id: 8,
    description: "T16 L",
    long_description:
      "Transpaletat LINDE të serisë T16 L të pajisura edhe mekanizmin për ngritjen e ngarkesës deri në 675 mm thjeshtojnë shumë punën në rastet e përzgjedhjes së rastësishme të ngarkesave të porositura. Me anë të këtyre pajisjeve operatori mund t'a ngrejë ngarkesën në lartësi komode duke e bërë më të thjeshtë sistemimin ose marrjen e mallrave nga raftet. Struktura prej çeliku e këtyre transpaletave është shumë e fortë gjë që bën që mjeti të jetë rezistent ndaj dëmtimeve dhe ndaj përdorimit të vazhdueshëm. Shasia e ulët e këtyre transpaletave garanton sigurinë e këmbëve të operatorit. Motori elektrik tre-fazor i këtyre mjeteve është i fuqishëm dhe garanton një përshpejtim të mirë të mjetit edhe kur ai është i ngarkuar me ngarkesën maksimale prej 1600 kg. Përsa i përket ngritjes së ngarkesave në lartësinë deri në 675 mm ngarkesa maksimale duhet të jetë jo më shumë se 800 kg.",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 675,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "08 T16L",
    photo: "08_T16L",
  },
  {
    id: 9,
    description: "T25 – T30",
    lifting_capacity_kg: 3000,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "09 T25-T30",
    photo: "09_T25-T30",
  },
  {
    id: 10,
    description: "T16 – T20 P",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "10 T16 T20P",
    photo: "10_T16_T20P",
  },
  {
    id: 11,
    description: "T20 – T25 AP N",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: true,
    pdf_file: "11 T20-T25APN",
    photo: "11_T20-T25APN",
  },
  {
    id: 12,
    description: "T20 – T25 AP",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "12 T20-T25AP",
    photo: "12_T20-T25AP",
  },
  {
    id: 13,
    description: "T20 – T25 FP",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "13 T20-T25FP",
    photo: "13_T20-T25FP",
  },
  {
    id: 14,
    description: "T20 – T25 SP",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "14 T20-T25SP",
    photo: "14_T20-T25SP",
  },
  {
    id: 15,
    description: "T20 – T25 SR",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "15 T20-T25SR",
    photo: "15_T20-T25SR",
  },
  {
    id: 16,
    description: "T14 S – T25 S/F",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "16 T20-T25S:F",
    photo: "16_T20-T25S:F",
  },
  {
    id: 17,
    description: "T20 – T25 R",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "17 T20-T25R",
    photo: "17_T20-T25R",
  },
  {
    id: 18,
    description: "T20 – T25 RW",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 125,
    movement_system: "Elektrik",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "18 T20-T25RW",
    photo: "18_T20-T25RW",
  },
  {
    id: 19,
    description: "P20",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "19 P20",
    photo: "19_P20",
  },
  {
    id: 20,
    description: "P40 – P60 C",
    lifting_capacity_kg: 6000,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "20 P40-P60C",
    photo: "20_P40-P60C",
  },
  {
    id: 21,
    description: "P60 – P80",
    lifting_capacity_kg: 200,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "21 P60-P80",
    photo: "21_P60-P80",
  },
  {
    id: 22,
    description: "P120 – P350",
    lifting_capacity_kg: 300,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "22 P120-P350",
    photo: "22_P120-P350",
  },
  {
    id: 23,
    description: "W20 – W30",
    lifting_capacity_kg: 3000,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Terheqes ngarkesash",
    ex_protection: false,
    pdf_file: "23 W20-W30",
    photo: "23_W20-W30",
  },
  {
    id: 24,
    description: "R10 – R16 B",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 7710,
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "24 R 10-R16B",
    photo: "24_R10-R16B",
  },
  {
    id: 25,
    description: "R14 – R25",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 14955,
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: true,
    pdf_file: "25 R14-R25",
    photo: "25_R14-R25",
  },
  {
    id: 26,
    description: "R14 – R20 G",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 7710,
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "26 R14-R20G",
    photo: "26_R14-R20G",
  },
  {
    id: 27,
    description: "R14 – R17 X",
    lifting_capacity_kg: 1700,
    lifting_height_mm: 12755,
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "27 R14-R17X",
    photo: "27_R14-R17X",
  },
  {
    id: 28,
    description: "R20 – R25 F",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 9650,
    movement_system: "Elektrik",
    product_type: "Stivues ngarkesash",
    ex_protection: false,
    pdf_file: "28 R20-R25F",
    photo: "28_R20-R25F",
  },
  {
    id: 29,
    description: "A",
    lifting_capacity_kg: 1500,
    lifting_height_mm: 12850,
    movement_system: "Elektrik",
    product_type: "Stivues per hapsira te ngushta",
    ex_protection: false,
    pdf_file: "29 A",
    photo: "29_A",
  },
  {
    id: 30,
    description: "K",
    lifting_capacity_kg: 1500,
    lifting_height_mm: 18110,
    movement_system: "Elektrik",
    product_type: "Stivues per hapsira te ngushta",
    ex_protection: true,
    pdf_file: "30 K",
    photo: "30_K",
  },
  {
    id: 31,
    description: "ML10 / MM10",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 3227,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "31 ML10:MM10",
    photo: "31_ML10:MM10",
  },
  {
    id: 32,
    description: "L10 – L16 B",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 5466,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "32 L10-L16B",
    photo: "32_L10-L16B",
  },
  {
    id: 33,
    description: "L14 – L20",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 6216,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "33 L14-L20",
    photo: "33_L14-L20",
  },
  {
    id: 34,
    description: "L14 – L20 AP",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 6216,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "34 L14-L20AP",
    photo: "34_L14-L20AP",
  },
  {
    id: 35,
    description: "L14 – L16 SP",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 5316,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "35 L14-L16SP",
    photo: "35_L14-L16SP",
  },
  {
    id: 36,
    description: "L14 – L16 R/Ri",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 5316,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "36 L14-L16R:RI",
    photo: "36_L14-L16R:RI",
  },
  {
    id: 37,
    description: "L14 – L16 RW",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 6216,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "37 L14-L16RW",
    photo: "37_L14-L16RW",
  },
  {
    id: 38,
    description: "L10 – L12 B AS",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 4686,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "38 L10-L12BAS",
    photo: "38_L10-L12BAS",
  },
  {
    id: 39,
    description: "L14 – L16 AS/AS AP",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 5316,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "39 L14-L16AS:ASAP",
    photo: "39_L14-L16AS:ASAP",
  },
  {
    id: 40,
    description: "L06 – L16 AC",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 4266,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "40 L06-L16AC",
    photo: "40_L06-L16AC",
  },
  {
    id: 41,
    description: "D06 – D10",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 2024,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "41 D06-D10",
    photo: "41_D06-D10",
  },
  {
    id: 42,
    description: "D08 M",
    lifting_capacity_kg: 1800,
    lifting_height_mm: 1590,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "42 D08M",
    photo: "42_D08M",
  },
  {
    id: 43,
    description: "D10",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 2424,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "43 D10",
    photo: "43_D10",
  },
  {
    id: 44,
    description: "D10 AP",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 2424,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "44 D10AP",
    photo: "44_D10AP",
  },
  {
    id: 45,
    description: "D10 FP",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 2424,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "45 D10FP",
    photo: "45_D10FP",
  },
  {
    id: 46,
    description: "D12 – D14",
    lifting_capacity_kg: 1400,
    lifting_height_mm: 4266,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "46 D12-D14",
    photo: "46_D12-D14",
  },
  {
    id: 47,
    description: "D12 – D14 AP",
    lifting_capacity_kg: 1400,
    lifting_height_mm: 4266,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: true,
    pdf_file: "47 D12-D14AP",
    photo: "47_D12-D14AP",
  },
  {
    id: 48,
    description: "D12 HP AP",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 2424,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "48 D12HPAP",
    photo: "48_D12HPAP",
  },
  {
    id: 49,
    description: "D12 – D14 SP",
    lifting_capacity_kg: 1400,
    lifting_height_mm: 4266,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "49 D12-D14SP",
    photo: "49_D12-D14SP",
  },
  {
    id: 50,
    description: "D12 HP SP",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 2424,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "50 D12HPSP",
    photo: "50_D12HPSP",
  },
  {
    id: 51,
    description: "D12 S – D12 SF",
    lifting_capacity_kg: 1800,
    lifting_height_mm: 1724,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "51 D12S-D12SF",
    photo: "51_D12S-D12SF",
  },
  {
    id: 52,
    description: "D12 R",
    long_description:
      "Trans-Stivuesit e paletave LINDE të serisë D12 R transportojnë njëkohësisht dy paleta nga 1000 kg sejcila dhe arrin një shpejtësi lëvizje deri në 12 km/orë, falë motorit elektrik tre-fazor me fuqi 3 kW. Këto cilësi e bëjnë këtë mjet veçanërisht të përshtatshëm për transportimin e mallrave në largësi mesatare dhe në largësi të mëdha, kur kërkohet produktivitet i lartë. Si rezultat i ngritjes iniciale, këto mjete janë të përshtatshme edhe për ngarkimin dhe shkarkimin e kamionëve. Kontrolli i këtyre mjeteve është preçiz ndaj dhe menaxhimi i tyre është shumë i sigurtë, komod dhe produktiv. Falë strukturës së telaios së tyre dhe manovrueshmërisë së shkëlqyer, trans-stivuesit e serisë D12 R mund përdoren në mënyrë të sigurtë dhe të shpejtë edhe në hapësirat e ngushta. Pozicioni i ngritur i sediljes së operatorit që është në kënd të drejtë me drejtimin e lëvizjes i ofron operatorit një fushëpamje më të gjerë si për lëvizjen para ashtu edhe për lëvizjen mbrapa. I ulur në sedilhen e mjetit operatori në këtë mënyrë ka edhe kontroll më të madh mbi ngarkesën.",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 2344,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "52 D12R",
    photo: "52_D12R",
  },
  {
    id: 53,
    description: "D12 RW",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 2844,
    movement_system: "Elektrik",
    product_type: "Transpalet stivuese",
    ex_protection: false,
    pdf_file: "53 D12RW",
    photo: "53_D12RW",
  },
  {
    id: 54,
    description: "N20 – N25 HP",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "54 N20-N25HP",
    photo: "54_N20-N25HP",
  },
  {
    id: 55,
    description: "N16 Li",
    long_description: "Ju lutemi të Konsultohuni me EMC shpk",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 675,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "55 N16LI",
    photo: "55_N16LI",
  },
  {
    id: 56,
    description: "N20 D",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 1924,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "56 N20D",
    photo: "56_N20D",
  },
  {
    id: 57,
    description: "N20 LoL",
    long_description:
      "Order Pickers (mjet për formimin e porosisë) LINDE të serisë N20 LoL, janë të pajisur me një strukturë që ngrihet, me anë të një mekanizmi gërshërë, në lartësinë e duhur me qëllim që vendosja e mallrave mbi paletë të bëhet pa e përkulur trupin. Tek këto mjete mund të ngarkohen dy paleta njëkohësisht. Paleta e parë vendoset mbi mekanizmin që ngrihet në lartësinë e trupit të njeriut, ndërsa paleta e dytë bosh vendoset në mjet vertikalisht në pjesën fundore të tij (afër kollonës). Në këtë mënyrë kur paleta e parë mbushet, ajo ulet, shtyhet në pjesën e parë të pirunëve, ndërsa paleta e dytë shtrihet mbi strukturën që ngrihet për t'u mbushur më tej nga operatori me mallrat që formojnë porosinë. Pra ky mjet është projektuar për të lehtësuar punën e operatorit me qëllim rritjen e efektivitetit në punë. Gjatë proçesit të punës ky mjet mund të komandohet nga të dy anët për lëvizje me shpejtësinë në këmbë me qëllim që operatori nga një raft tek tjetri të lëviz mjetin pa hypur sipër tij. Opsione të shumta, në varësi të nevojave dhe kërkesave të klientëve mund t'i shtohen këtyre mjeteve.",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 1612,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "57 N20LoL",
    photo: "57_N20LoL",
  },
  {
    id: 58,
    description: "N20 XL",
    lifting_capacity_kg: 600,
    lifting_height_mm: 750,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "58 N20XL",
    photo: "58_N20XL",
  },
  {
    id: 59,
    description: "N20 – N25 C",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 130,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "59 N20-N25C",
    photo: "59_N20-N25C",
  },
  {
    id: 60,
    description: "N20 C L",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 700,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "60 N20CL",
    photo: "60_N20CL",
  },
  {
    id: 61,
    description: "N20 C D",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 1580,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "61 N20CD",
    photo: "61_N20CD",
  },
  {
    id: 62,
    description: "N20 C LoL",
    long_description:
      "Order Pickers (mjet për formimin e porosisë) LINDE të serisë N20 C LoL bën të mundur ngritjen dhe transportimin e dy paletave njëkohësisht në një rrugë të vetme, falë pirunëve të gjatë që ata kanë dhe strukturës shtesë që ngrihet. Fillimisht operatori fillon të mbushë një paletë, duke e ngritur atë në lartësinë e dëshiruar ndërkohë që paleta e dytë fiksohet në pirunë me një pajisje të veçantë. Pasi paleta e parë mbushet, atëherë ajo ulet dhe spostohet përpara tek majat e mirunit, për t'i bëtë vend paletës së dytë që të mbushet me mallrat që dihet të krijojnë porosinë. Pra ky mjet është projektuar për të lehtësuar punën e operatorit me qëllim rritjen e efektivitetit në punë. Gjatë proçesit të punës ky mjet mund të komandohet nga të dy anët për lëvizje me shpejtësinë në këmbë me qëllim që operatori nga një raft tek tjetri të lëviz mjetin pa hypur sipër tij. Gjithashtu është edhe opsioni i platformës ngritëse të operatorit për të bërë të mundur marrjen e mallrave që gjenden në nivelin e parë dhe të dytë të rafteve. Ngritja iniciale lejon që këto mjete të mund të lëvizin pa problem edhe në rampat e pjerrëta dhe në terrenet me sipërfaqe të parregullt.",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 800,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "62 N20CLoL",
    photo: "62_N20CLoL",
  },
  {
    id: 63,
    description: "N20 C LX",
    long_description:
      "Order Pickers (mjet për formimin e porosisë) LINDE të serisë N20 C LX janë mjete me pirunë që ngrihen me mekanizëm në formë gërshëre. Ato janë të afta të ngrenë dhe të transportojnë materiale të vendosura mbi paleta apo mbi kontenierë të posaçëm mallra me peshë deri në 2000 kg. Gjatë punës për formimin e ngarkesave operatori i ngre pirunët në lartësin e trupit me qëllim që ta ngarkojë apo t'a shkarkojë mjetin pa patur nevojë të përkulet në mënyrë të vazhdueshme. Në këtë mënyrë operatori shkon në çdo vend të magazinës për të ngarkuar në mjet të gjitha mallrat që janë të evidentuara tek lista e porosisë pa u lodhur dhe pa patur dëmtime të shtyllës kurrizore. Në këto mjete mund të vendoset edhe opsioni i ngritjes së platformës së operatorit, me qëllim që ai të mund të arrij të marrë ato mallra që janë të stivuara në katet e larta të rafteve të magazinës. Nga ana tjetër tek këto mjete i është kushtuar vëmendje e veçantë kompartimentit të punës së operatorit, me qëllim që sforcot fizike të jenë sa me të vogla dhe rendimenti në punë të jetë sa më i madh.",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 700,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "63N20CLX",
    photo: "63N20CLX",
  },
  {
    id: 64,
    description: "V08",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 1877,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "64 V08",
    photo: "64_V08",
  },
  {
    id: 65,
    description: "V10",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 5415,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "65 V10",
    photo: "65_V10",
  },
  {
    id: 66,
    description: "V modular B",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 6865,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "66 VmodularB",
    photo: "66_VmodularB",
  },
  {
    id: 67,
    description: "V modular",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 12660,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "67 Vmodular",
    photo: "67_Vmodular",
  },
  {
    id: 68,
    description: "MV01",
    lifting_capacity_kg: 100,
    lifting_height_mm: 3620,
    movement_system: "Elektrik",
    product_type: "Komisionues Transpalet",
    ex_protection: false,
    pdf_file: "68 MV01",
    photo: "68_MV01",
  },
  {
    id: 69,
    description: "E 10",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 5400,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "69 E10",
    photo: "69_E10",
  },
  {
    id: 70,
    description: "Xi10 – Xi20",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 8000,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "70 Xi10-Xi20",
    photo: "70_Xi10-Xi20",
  },
  {
    id: 71,
    description: "E14 – E20",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 8000,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "71 E14-E20",
    photo: "71_E14-E20",
  },
  {
    id: 72,
    description: "Xi16 – Xi20 P",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 8000,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "72 Xi16-Xi20P",
    photo: "72_Xi16-Xi20P",
  },
  {
    id: 73,
    description: "E16 – E20 P",
    lifting_capacity_kg: 2000,
    lifting_height_mm: 8000,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "73 E16-E20P",
    photo: "73_E16-E20P",
  },
  {
    id: 74,
    description: "X20 – X35",
    lifting_capacity_kg: 3500,
    lifting_height_mm: 7780,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "74 X20-X35",
    photo: "74_X20-X35",
  },
  {
    id: 75,
    description: "E20 – E35",
    lifting_capacity_kg: 3500,
    lifting_height_mm: 7780,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: true,
    pdf_file: "no datasheet",
    photo: "75_E20-E35",
  },
  {
    id: 76,
    description: "X35 – X50",
    lifting_capacity_kg: 5000,
    lifting_height_mm: 7665,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "76 X35-X50",
    photo: "76_X35-X50",
  },
  {
    id: 77,
    description: "E35 – E50",
    lifting_capacity_kg: 5000,
    lifting_height_mm: 7665,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: true,
    pdf_file: "77 E35-E50",
    photo: "77_E35-E50",
  },
  {
    id: 78,
    description: "E60 – E80",
    lifting_capacity_kg: 8000,
    lifting_height_mm: 8670,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "78 E60-E80",
    photo: "78_E60-E80",
  },
  {
    id: 79,
    description: "E100 – E180",
    lifting_capacity_kg: 18000,
    lifting_height_mm: 7000,
    movement_system: "Elektrik",
    product_type: "Pirun elektrik",
    ex_protection: false,
    pdf_file: "79 E100-E180",
    photo: "79_E100-E180",
  },
  {
    id: 80,
    description: "H16 – H20",
    lifting_capacity_kg: 2050,
    lifting_height_mm: 6475,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "no datasheet",
    photo: "80_H16-H20",
  },
  {
    id: 81,
    description: "H20 – H35",
    lifting_capacity_kg: 3500,
    lifting_height_mm: 7780,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "81 H20-H35",
    photo: "81_H20-H35",
  },
  {
    id: 82,
    description: "H35 – H50",
    lifting_capacity_kg: 5000,
    lifting_height_mm: 7665,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "82 H35-H50",
    photo: "82_H35-H50",
  },
  {
    id: 83,
    description: "H50 – H80",
    lifting_capacity_kg: 8000,
    lifting_height_mm: 9655,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "83 H50-H80",
    photo: "83_H50-H80",
  },
  {
    id: 84,
    description: "H100 – H180 D",
    lifting_capacity_kg: 18000,
    lifting_height_mm: 9500,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "84 H100-H180D",
    photo: "84_H100-H180D",
  },
  {
    id: 85,
    description: "HT100 – HT180 D",
    lifting_capacity_kg: 18000,
    lifting_height_mm: 9500,
    movement_system: "Nafte/Gaz",
    product_type: "Pirun me nafte/gaz",
    ex_protection: false,
    pdf_file: "85 HT100-HT180D",
    photo: "85_HT100-HT180D",
  },
  {
    id: 86,
    description: "LT06 – LT10 M / LT10 W",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 40,
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "86 LT06-LT10M:LT10W",
    photo: "86_LT06-LT10M:LT10W",
  },
  {
    id: 87,
    description: "LT10 – LT20 C / LT10 – LT16 B/BM",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 60,
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "87 LT10-LT20C:LT10-LT16B:BM",
    photo: "87_LT10-LT20C:LT10-LT16B:BM",
  },
  {
    id: 88,
    description: "LT16 Ch/BMh",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 115,
    movement_system: "Elektrik",
    product_type: "Tren terheqes per magazine",
    ex_protection: false,
    pdf_file: "88 LT16Ch:BMh",
    photo: "88_LT16Ch:BMh",
  },
  {
    id: 89,
    description: "C-MATIC",
    lifting_capacity_kg: 1500,
    lifting_height_mm: 60,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "89 C-MATIC",
    photo: "89_C-MATIC",
  },
  {
    id: 90,
    description: "C-MATIC HP",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 40,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "90 C-MATICHP",
    photo: "90_C-MATICHP",
  },
  {
    id: 91,
    description: "L-MATIC core",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 1844,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "91 L-MATICcore",
    photo: "91_L-MATICcore",
  },
  {
    id: 92,
    description: "L-MATIC",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 1924,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "92 L-MATIC",
    photo: "92_L-MATIC",
  },
  {
    id: 93,
    description: "L-MATIC HD/HD k",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 3500,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "93 L-MATICHD:HDk",
    photo: "93_L-MATICHD:HDk",
  },
  {
    id: 94,
    description: "L-MATIC AC",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 4144,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "94 L-MATICAC",
    photo: "94_L-MATICAC",
  },
  {
    id: 95,
    description: "P-MATIC",
    lifting_capacity_kg: 5000,
    lifting_height_mm: 0,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "95 P-MATIC",
    photo: "95_P-MATIC",
  },
  {
    id: 96,
    description: "R-MATIC",
    lifting_capacity_kg: 1600,
    lifting_height_mm: 11455,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "96 R-MATIC",
    photo: "96_R-MATIC",
  },
  {
    id: 97,
    description: "K-MATIC",
    lifting_capacity_kg: 1450,
    lifting_height_mm: 14000,
    movement_system: "Elektrik",
    product_type: "Mjete automatike",
    ex_protection: false,
    pdf_file: "97 K-MATIC",
    photo: "97_K-MATIC",
  },
];
