export const products = [
  {
    id: 3,
    description: "Linde MT15C",
    product_type: "Transpalete",
    movement_system: "Elektrik",
    lifting_capacity_kg: 1500,
    lifting_height_mm: 115,
    fork_length_mm: 1150,
    condition: "E re",
    hours_used: 0,
    battery: "Lithium 24V",
    version: "Standart",
    internal_code: "02 MT15C",
    photo: "mt15c",
    product_url: "https://www.linde-mh.com/en/Products/Pallet-Trucks/MT15-C/",
    available: true,
    shop_url: "https://www.gruma.de/en/shop/p/niederhubwagen-linde-mt15-c/",
  },
  {
    id: 4,
    description: "Linde N20",
    product_type: "Komisionues transpalete",
    movement_system: "Elektrik",
    lifting_capacity_kg: 2500,
    lifting_height_mm: 115,
    fork_length_mm: 1150,
    condition: "E re",
    hours_used: 0,
    battery: "Lithium 24V",
    version: "Standart",
    internal_code: "54 N20-N25HP",
    photo: "n20",
    product_url: "N20",
    available: true,
    shop_url: null,
  },
  {
    id: 5,
    description: "Linde MT12",
    product_type: "Transpalete",
    movement_system: "Elektrik",
    lifting_capacity_kg: 1200,
    lifting_height_mm: 115,
    fork_length_mm: 1150,
    condition: "E re",
    hours_used: 0,
    battery: "Lithium 24V",
    version: "Standart",
    photo: "mt12",
    internal_code: "-",
    product_url: "MT12",
    available: true,
    shop_url: null,
  },
];
