export const products = [
  {
    id: 5000,
    description: "M10 X/XE",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 715,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "01 M10X:XE",
    photo: "01_M10X_XE",
    price: 1000,
    available: true,
  },
  {
    id: 50001,
    description: "M10 X/XE",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 715,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "01 M10X:XE",
    photo: "01_M10X_XE",
    price: 1000,
    available: false,
  },
  {
    id: 50312,
    description: "M10 X/XE",
    lifting_capacity_kg: 1000,
    lifting_height_mm: 715,
    movement_system: "Manual",
    product_type: "Transpalete",
    ex_protection: false,
    pdf_file: "01 M10X:XE",
    photo: "01_M10X_XE",
    price: 1000,
    available: true,
  },
];
